[package]
name = "bevy_play"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.2", features = ["wayland"] }
bms-rs = "0.9.0"
encoding_rs = "0.8.35"
num-traits = "0.2.19"
rand = "0.9.2"
